---
fixtures:
  repositories:
    augeas_core: https://github.com/puppetlabs/puppetlabs-augeas_core.git
    concat: https://github.com/puppetlabs/puppetlabs-concat.git
    stdlib: https://github.com/puppetlabs/puppetlabs-stdlib.git
    yumrepo_core: https://github.com/puppetlabs/puppetlabs-yumrepo_core.git
